# Author: Tom Sapletta · Part of the ifURI solution — GENERATED by urirun-reasoner.
"""urirun-connector-youtube — Headless YouTube access via yt-dlp: fetch transcript/captions, video metadata, and chapter-based highlights. No browser, no API key, no secrets.

Generated autonomously to satisfy a capability the reasoner found blocked (no connector
served the youtube:// scheme). Built to URI_NATIVE_CONNECTOR_CHECKLIST: lazy imports,
handlers never raise (urirun envelope), queries in-process.
"""
from __future__ import annotations

from typing import Any

import urirun

from . import _urirun_compat

CONNECTOR_ID = "youtube"
conn = _urirun_compat.connector(CONNECTOR_ID, scheme="youtube")


def _ok(**kw: Any) -> dict[str, Any]:
    return urirun.ok(connector=CONNECTOR_ID, **kw)


def _fail(msg: str, action: str, **extra: Any) -> dict[str, Any]:
    return urirun.fail(msg, connector=CONNECTOR_ID, action=action, **extra)


@conn.handler("transcript/query/fetch", isolated=False,
              meta={"label": "Fetch transcript/captions for a YouTube video (headless, no API key)"})
def transcript_query_fetch(url: str = '', lang: str = 'en', format: str = 'txt') -> dict[str, Any]:
    """Fetch transcript/captions for a YouTube video (headless, no API key)"""
    try:
        if not url: return _fail('url is required', 'transcript-fetch')
        try: from yt_dlp import YoutubeDL
        except Exception as exc: return _fail(f'yt-dlp not available: {exc}', 'transcript-fetch')
        import json, re, urllib.request
        want = lang or 'en'
        opts = {'writesubtitles': True, 'writeautomaticsub': True, 'skip_download': True, 'quiet': True, 'no_warnings': True, 'noplaylist': True, 'subtitleslangs': [want, want.split('-')[0], 'en']}
        with YoutubeDL(opts) as ydl: info = ydl.extract_info(url, download=False) or {}
        tracks = {}
        for src in (info.get('subtitles') or {}, info.get('automatic_captions') or {}):
            for lng, entries in (src or {}).items(): tracks.setdefault(lng, []).extend(entries or [])
        if not tracks: return _fail('no captions/subtitles available for this video', 'transcript-fetch')
        def _rank(lng):
            base, wbase = lng.split('-')[0].lower(), want.split('-')[0].lower()
            if lng.lower() == want.lower(): return 0
            if base == wbase: return 1
            return 2
        ordered = sorted(tracks.keys(), key=lambda l: (_rank(l), l))
        picked_url, picked_ext, picked_lang = '', '', ''
        for lng in ordered:
            for ext in ('json3', 'vtt', 'ttml'):
                for e in tracks[lng]:
                    if e.get('ext') == ext and e.get('url'):
                        picked_url, picked_ext, picked_lang = e['url'], ext, lng
                if picked_url: break
            if picked_url: break
        if not picked_url: return _fail('caption track found but no downloadable url', 'transcript-fetch')
        raw = urllib.request.urlopen(picked_url, timeout=30).read().decode('utf-8', 'replace')
        segments = []
        if picked_ext == 'json3':
            for ev in (json.loads(raw).get('events') or []):
                start = ev.get('tStartMs', 0) / 1000.0
                dur = ev.get('dDurationMs', 0) / 1000.0
                text = ''.join(s.get('utf8', '') for s in ev.get('segs', [])).strip()
                if text: segments.append({'start': round(start, 3), 'dur': round(dur, 3), 'text': text})
        else:
            cur_start = None
            for line in raw.splitlines():
                m = re.match(r'(\d+):(\d{2}):(\d{2})[.\d]*\s*-->\s*(\d+):(\d{2}):(\d{2})', line.strip())
                if m:
                    cur_start = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
                    continue
                t = line.strip()
                if t and '-->' not in t and not t.isdigit() and not t.startswith('WEBVTT') and cur_start is not None:
                    segments.append({'start': float(cur_start), 'dur': 0.0, 'text': t})
        plain = ' '.join(s['text'] for s in segments)
        base = _ok(action='transcript-fetch', url=url, lang=picked_lang, ext=picked_ext, segment_count=len(segments), segments=segments, transcript=plain)
        return base if format == 'json' else {k: base[k] for k in ('ok', 'connector', 'action', 'url', 'lang', 'ext', 'segment_count', 'transcript')}
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "youtube-transcript_query_fetch")


@conn.handler("video/query/metadata", isolated=False,
              meta={"label": "Fetch YouTube video metadata (title, duration, chapters) - headless"})
def video_query_metadata(url: str = '') -> dict[str, Any]:
    """Fetch YouTube video metadata (title, duration, chapters) - headless"""
    try:
        if not url: return _fail('url is required', 'video-metadata')
        try: from yt_dlp import YoutubeDL
        except Exception as exc: return _fail(f'yt-dlp not available: {exc}', 'video-metadata')
        opts = {'skip_download': True, 'quiet': True, 'no_warnings': True, 'noplaylist': True}
        with YoutubeDL(opts) as ydl: info = ydl.extract_info(url, download=False) or {}
        chapters = []
        for c in (info.get('chapters') or []):
            chapters.append({'start': round(float(c.get('start_time', 0)), 3), 'end': round(float(c.get('end_time', 0)), 3), 'title': c.get('title', '')})
        desc = info.get('description') or ''
        return _ok(action='video-metadata', url=url, id=info.get('id', ''), title=info.get('title', ''), channel=(info.get('uploader') or info.get('channel') or ''), duration=info.get('duration'), view_count=info.get('view_count'), like_count=info.get('like_count'), upload_date=info.get('upload_date'), tags=(info.get('tags') or []), chapters=chapters, description=desc[:500])
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "youtube-video_query_metadata")


@conn.handler("highlights/query/extract", isolated=False,
              meta={"label": "Extract highlight moments from chapters (or transcript density) - verifiable, no LLM"})
def highlights_query_extract(url: str = '', lang: str = 'en', max_items: int = 8) -> dict[str, Any]:
    """Extract highlight moments from chapters (or transcript density) - verifiable, no LLM"""
    try:
        if not url: return _fail('url is required', 'highlights-extract')
        try: from yt_dlp import YoutubeDL
        except Exception as exc: return _fail(f'yt-dlp not available: {exc}', 'highlights-extract')
        import json, re, urllib.request
        opts = {'skip_download': True, 'writesubtitles': True, 'writeautomaticsub': True, 'quiet': True, 'no_warnings': True, 'noplaylist': True, 'subtitleslangs': [lang or 'en']}
        with YoutubeDL(opts) as ydl: info = ydl.extract_info(url, download=False) or {}
        chapters = info.get('chapters') or []
        if chapters:
            out = []
            for c in chapters:
                if c.get('title'):
                    out.append({'start': round(float(c.get('start_time', 0)), 3), 'end': round(float(c.get('end_time', 0)), 3), 'title': c.get('title', ''), 'source': 'chapter'})
                if len(out) >= max_items: break
            return _ok(action='highlights-extract', url=url, source='chapters', highlight_count=len(out), highlights=out)
        duration = float(info.get('duration') or 0)
        tracks = {}
        for src in (info.get('subtitles') or {}, info.get('automatic_captions') or {}):
            for lng, entries in (src or {}).items(): tracks.setdefault(lng, []).extend(entries or [])
        seg_url, seg_ext = '', ''
        for lng in sorted(tracks.keys()):
            for ext in ('json3', 'vtt'):
                for e in tracks.get(lng, []):
                    if e.get('ext') == ext and e.get('url'):
                        seg_url, seg_ext = e['url'], ext
                if seg_url: break
            if seg_url: break
        if not seg_url or duration <= 0:
            return _fail('no chapters and no caption track to derive highlights from', 'highlights-extract')
        raw = urllib.request.urlopen(seg_url, timeout=30).read().decode('utf-8', 'replace')
        words = []
        if seg_ext == 'json3':
            for ev in (json.loads(raw).get('events') or []):
                t = ''.join(s.get('utf8', '') for s in ev.get('segs', [])).strip()
                if t and ev.get('tStartMs') is not None: words.append((ev.get('tStartMs', 0) / 1000.0, len(t.split())))
        else:
            cur = None
            for line in raw.splitlines():
                mm = re.match(r'(\d+):(\d{2}):(\d{2})', line.strip())
                if mm: cur = int(mm.group(1)) * 3600 + int(mm.group(2)) * 60 + int(mm.group(3))
                elif cur is not None and line.strip() and '-->' not in line: words.append((float(cur), len(line.split())))
        buckets = max(8, max_items * 2)
        span = duration / buckets
        scores = []
        for i in range(buckets):
            lo, hi = i * span, (i + 1) * span
            n = sum(w for ts, w in words if lo <= ts < hi)
            if n: scores.append((n, i, lo, hi))
        scores.sort(reverse=True)
        top = sorted(scores[:max_items], key=lambda x: x[1])
        out = [{'start': round(lo, 3), 'end': round(hi, 3), 'title': f'dense segment {i+1}/{buckets}', 'words': n, 'source': 'density'} for n, i, lo, hi in top]
        return _ok(action='highlights-extract', url=url, source='transcript-density', highlight_count=len(out), highlights=out)
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "youtube-highlights_query_extract")


def urirun_bindings() -> dict[str, Any]:
    return conn.bindings()

@conn.handler("youtube://host/doctor/query/report", isolated=True, meta={"label": "Connector readiness report"})
def doctor() -> dict[str, Any]:
    """Return a safe, read-only connector readiness report for CI smoke tests."""
    return {
        "ok": True,
        "connector": CONNECTOR_ID,
        "version": _connector_version(),
        "status": "ready",
    }


def _connector_version() -> str:
    try:
        from importlib.metadata import version

        return version("urirun-connector-youtube")
    except Exception:
        return "0.1.0"


def connector_manifest() -> dict[str, Any]:
    return _urirun_compat.load_manifest(__package__) or {"id": CONNECTOR_ID}


def main(argv: list[str] | None = None) -> int:
    return conn.cli(argv, manifest_prose=_urirun_compat.load_manifest(__package__))


if __name__ == "__main__":
    raise SystemExit(main())
